/*
 - Extract bits using fields in a structure (struct)
 - The fields map into:
     15  14  13  12  11  10  9   8   7   6   5   4   3   2   1   0
   | A | A | B | B . B | B | C | C . C | C | C | D . E | E | E | E |

 - We must overlay the structure and the value using a union.
 - ECED 3403
 - 22 May 21
*/

#include "Bit Extraction.h"

/*
 - Struct with fields to extract bits
 - <type< <name> : <size>
 - The <type> is any integer type (char, short, int, long, unsigned)
 - Advisable to use unsigned to avoid sign extension
 - <name> is the field name
 - <size> is the number of bits
 - Move from LSBit (0, rightmost) to MSbit (15, leftmost) 
*/
struct mask
{
unsigned e : 4;
unsigned d : 1;
unsigned c : 5;
unsigned b : 4;
unsigned a : 2;
};

/*
 - Union (overlay) of an int and struct mask
*/
union olay
{
int data;
struct mask bits;
};

void struct_bits_1(int bits[], int value)
{
/*
 - Bits[] is an array corresponding to each bit value
 - Value contains the bits to be extracted
 - Oilof is an overlay with two fields, a int and struct mask
 - The fields in oilof must be specified
 - The shifting and masking operations are generated by compiler
*/
union olay oilof;

/* First, assign the value to the int in oilof */
oilof . data = value;

/* Second, extract the bits of value using mask */
bits[0] = oilof.bits.a;
bits[1] = oilof.bits.b;
bits[2] = oilof.bits.c;
bits[3] = oilof.bits.d;
bits[4] = oilof.bits.e;

}

void struct_bits_2(int bits[], int value)
{
/*
 - Bits[] is an array corresponding to each bit value
 - Value contains the bits to be extracted
 - Shifting and masking code generated by compiler
*/
struct mask *overlay;

/* Must make overlay point to contents of value */
overlay = (struct mask *) &value;

/* 
 - Extract bit values 
 - Overlay is the base address, fields are offsets from that address
*/
bits[0] = overlay -> a;
bits[1] = overlay -> b;
bits[2] = overlay -> c;
bits[3] = overlay -> d;
bits[4] = overlay -> e;

}
